### PR TITLE
Repair: fix repair --host filtering

### LINKED ISSUE #3736: Incorrect repair --host node filtering
SM doesn't allow to repair with `--host` flag when table is not fully replicated (all tokens are on all hosts).
I was introduced when refactoring SM repair in `3.2.1`.
Ref https://github.com/scylladb/scylla-enterprise/issues/3948

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
Fixes #3736

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
Have yet to add a test for that.

**Comment by Michal-Leszczynski** [comment]
The following test was failing after changing repair test setup and passed after applying the fix:
```
=== RUN   TestServiceRepairIntegration/repair_host
--- When: run repair
--- Then: repair is running
13:04:25.232	INFO	Start generating target	{"task": "87f5bbe7-4483-4304-998c-ca04d95f3baf", "run": "acf1dfb4-dbb1-11ee-9625-0892040e83bb"}
13:04:25.279	INFO	End generating target	{"task": "87f5bbe7-4483-4304-998c-ca04d95f3baf", "run": "acf1dfb4-dbb1-11ee-9625-0892040e83bb", "error": "create repair plan: no replicas to repair"}
    service_repair_integration_test.go:1242: timeout 1m0s
    --- FAIL: TestServiceRepairIntegration/repair_host (60.01s)
```

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka why do we only test `2024.1.0.rc3` on PRs? I know that other versions are tested on push to master, but I think that it would be useful to see results of those tests before merging PRs to master.

**Comment by karol-kokoszka** [comment]
> @karol-kokoszka why do we only test 2024.1.0.rc3 on PRs? I know that other versions are tested on push to master, but I think that it would be useful to see results of those tests before merging PRs to master

There were too many of these checks on a single PR. They are part of merging to master branch now.
You can still execute these tests locally.

**Comment by karol-kokoszka** [comment]
Let's keep it as a check for the latest commercial release of Scylla that includes all variants.
Other version let be checked on master branch.

**Comment by Michal-Leszczynski** [comment]
Ok, btw this PR is ready for review

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka, actually, just pushed a small fix for a single node cluster, now it should be good to go.

**Review by karol-kokoszka — APPROVED** [review]
:+1:

**Pull request merged**
