### PR TITLE
add upgrade content

### PR DESCRIPTION
**Pull request by lauranovich**
Adds the Scylla Manager Upgrade guides to Scylla Manager. 
in going forward, we should limit what content appears in each version, but this move allows all of the upgrade content to live with the rest of the documentation. 

---

### CODE REVIEW

**Comment by mmatczuk** [comment]
Since we have it versioned let's add a single page describing the upgrade procedure avoid putting tons of archive pages on users.

**Review by mmatczuk — CHANGES_REQUESTED** [review]
.

**Comment by tzach** [comment]
@mmatczuk IMHO its better to have upgrade "outside" the versioning, so looking at 2.5, for example, I can find upgrades from 2.3 to 2.4 to 2.5 etc
It will make it easier for user to find, and for you to maintain.

**Comment by mmatczuk** [comment]
On a site for version 2.5 there shall be stuff only relevant to that version.

**Comment by lauranovich** [comment]
One question - do all of our users of Scylla Manager upgrade each time? 
OR do they wait and then upgrade meaning they upgrade 2 versions at the same time?
Once we know how our users upgrade, we can decide what to do w/ the older content

**Comment by mmatczuk** [comment]
You just upgrade the package with package manager and it just works.
If it does not work like that we are doing something wrong.

**Pull request closed without merging**
