### PR TITLE
Rclone: don't rely on cached bandwidth limit in configguard

### LINKED ISSUE #4119: Don't reset rclone rate limit when not needed
Rclone server has `globalConfigGuard` that should update rate limit / transfers used by the agent only when the update is actually changing the value. Otherwise, we perform unnecessary re-initialization, which might be costly.

Here are logs from an [SCT test](https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/view/Backup/job/no-delta-backup-test/9/console) running 2 backups and restore:
```
2024-10-28T13:30:00.620+00:00  {"L":"INFO","T":"2024-10-28T13:30:00.163Z","N":"rclone","M":"Location check done"}
2024-10-28T13:30:02.870+00:00  {"L":"INFO","T":"2024-10-28T13:30:02.606Z","N":"rclone","M":"Bandwidth limit set to {100M 100M}"}
2024-10-28T13:30:04.370+00:00  {"L":"INFO","T":"2024-10-28T13:30:04.021Z","N":"rclone","M":"Bandwidth limit set to {100M 100M}"}
2024-10-28T13:32:19.370+00:00  {"L":"INFO","T":"2024-10-28T13:32:19.015Z","N":"rclone","M":"Bandwidth limit set to {100M 100M}"}
2024-10-28T13:32:20.620+00:00  {"L":"INFO","T":"2024-10-28T13:32:20.307Z","N":"rclone","M":"Bandwidth limit set to {100M 100M}"}
2024-10-28T13:32:21.620+00:00  {"L":"INFO","T":"2024-10-28T13:32:21.340Z","N":"rclone","M":"Bandwidth limit set to {100M 100M}"}
2024-10-28T13:32:22.620+00:00  {"L":"INFO","T":"2024-10-28T13:32:22.424Z","N":"rclone","M":"Bandwidth limit set to {100M 100M}"}
2024-10-28T13:32:23.756+00:00  {"L":"INFO","T":"2024-10-28T13:32:23.585Z","N":"rclone","M":"Bandwidth limit set to {100M 100M}"}
2024-10-28T13:33:24.370+00:00  {"L":"INFO","T":"2024-10-28T13:33:23.905Z","N":"rclone","M":"Location check done"}
2024-10-28T13:33:25.620+00:00  {"L":"INFO","T":"2024-10-28T13:33:25.166Z","N":"rclone","M":"Bandwidth limit set to {100M 100M}"}
2024-10-28T13:33:26.790+00:00  {"L":"INFO","T":"2024-10-28T13:33:26.642Z","N":"rclone","M":"Bandwidth limit set to {100M 100M}"}
2024-10-28T13:33:26.790+00:00  {"L":"INFO","T":"2024-10-28T13:33:26.644Z","N":"rclone","M":"There was nothing to transfer"}
2024-10-28T13:33:41.870+00:00  {"L":"INFO","T":"2024-10-28T13:33:41.589Z","N":"rclone","M":"Location check done"}
2024-10-28T13:33:57.621+00:00  {"L":"INFO","T":"2024-10-28T13:33:57.183Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
2024-10-28T13:34:32.370+00:00  {"L":"INFO","T":"2024-10-28T13:34:32.105Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
2024-10-28T13:34:59.621+00:00  {"L":"INFO","T":"2024-10-28T13:34:59.513Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
2024-10-28T13:35:23.370+00:00  {"L":"INFO","T":"2024-10-28T13:35:23.040Z","M":"http: TLS handshake error from 10.12.1.124:45446: EOF"}
2024-10-28T13:35:27.871+00:00  {"L":"INFO","T":"2024-10-28T13:35:27.633Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
2024-10-28T13:35:57.120+00:00  {"L":"INFO","T":"2024-10-28T13:35:56.914Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
2024-10-28T13:36:28.621+00:00  {"L":"INFO","T":"2024-10-28T13:36:28.179Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
2024-10-28T13:36:58.120+00:00  {"L":"INFO","T":"2024-10-28T13:36:57.811Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
2024-10-28T13:37:33.621+00:00  {"L":"INFO","T":"2024-10-28T13:37:33.341Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
2024-10-28T13:37:58.620+00:00  {"L":"INFO","T":"2024-10-28T13:37:58.332Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
2024-10-28T13:38:12.871+00:00  {"L":"INFO","T":"2024-10-28T13:38:12.726Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
```
We can see that rate limit has been updated multiple times, even though there was no need for it.

In the implementation we can see:
```go
// SetBandwidthLimit sets global bandwidth limit in token bucket.
func SetBandwidthLimit(limit string) error {
	globalConfigGuard.mu.Lock()
	defer globalConfigGuard.mu.Unlock()
	globalConfigGuard.init()

	if limit == globalConfigGuard.bandwidthLimit {
		return nil
	}

	in := rc.Params{
		"rate": limit,
	}
	_, err := rcCalls.Get("core/bwlimit").Fn(context.Background(), in)
	if err != nil {
		return errors.Wrapf(err, "set bandwidth to %s", limit)
	}
	return nil
}
```
We simply forgot to update the value cached in `globalConfigGuard` after setting it with `core/bwlimit` call.

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
This PR fixes the way in which `configguard` checked if bandwidth limit should be updated.
Previously it was updating bandwidth limit with each Rclone call, now it updates it only when it's changed.

This PR also removes unnecessary usages of `RcloneSetBandwidthLimit`, as handling bandwidth limit should be done by specific Rclone calls.

Fixes #4119

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
Example agent logs from `TestRestoreFullIntegration` before the change:
```
{"L":"INFO","T":"2024-11-22T10:52:47.258Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
{"L":"INFO","T":"2024-11-22T10:52:57.568Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
{"L":"INFO","T":"2024-11-22T10:53:07.829Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
{"L":"INFO","T":"2024-11-22T10:53:17.901Z","N":"rclone","M":"Bandwidth limit reset to unlimited"}
```
And after the change:
```
{"L":"INFO","T":"2024-11-22T10:46:50.445Z","N":"rclone","M":"Bandwidth limit set to {999M 999M}"}
```
(changed bandwidth limit to 999M because otherwise we wouldn't see any log with bandwidth limit change, but that's expected)

**Comment by Michal-Leszczynski** [comment]
`TestPurgeIntegration` [failed](https://github.com/scylladb/scylla-manager/actions/runs/11971592996/job/33376737279?pr=4120), but it looks flaky and not related to this PR, but I will try to investigate it.

**Comment by Michal-Leszczynski** [comment]
> TestPurgeIntegration [failed](https://github.com/scylladb/scylla-manager/actions/runs/11971592996/job/33376737279?pr=4120), but it looks flaky and not related to this PR, but I will try to investigate it.

No luck with that - there is some chance that minio lagged when listing manifests just after their creation.

**Review by VAveryanov8 — APPROVED** [review]
LGTM

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka The PR is ready for review!

**Review by karol-kokoszka — APPROVED** [review]

**Pull request merged**
