### PR TITLE
Fix AWS S3 mentions to Amazon S3

### PR DESCRIPTION
**Pull request by hopugop**
Amazon official product guidelines names it Amazon S3. This PR fixes references in Scylla Manager documentation.

Fixes https://github.com/scylladb/scylla-manager/issues/3273

### CODE REVIEW

**Comment by tzach** [comment]
Doc preview generate a warning
```
/docs/source/backup/index.rst:62: WARNING: unknown document: setup-aws-s3
```

**Comment by tzach** [comment]
Please add the follwing line to https://github.com/scylladb/scylla-manager/blob/master/docs/_utils/redirects.yaml 

```
/backup/setup-aws-s3.html: /backup/setup-amazon-s3
```
It will redirect from the old path to the new one, in case anyone try to reach it

**Comment by tzach** [comment]
LGTM

**Comment by hopugop** [comment]
Tests passed!

**Review by karol-kokoszka — APPROVED** [review]
:+1:

**Pull request merged**
