### PR TITLE
Un-deprecate the `sctool backup files` CLI

### LINKED ISSUE #3996: "Undeprecate" `sctool backup files` command and provide the documentation
As per topic

### PR DESCRIPTION
**Pull request by karol-kokoszka**
Fixes #3996

This PR brings back the documentation of `sctool backup files` CLI which is very useful in terms of listing the contents of the snapshot.

---

Please make sure that:
- Code is split to commits that address a single change
- Commit messages are informative
- Commit titles have module prefix
- Commit titles have issue nr. suffix

### CODE REVIEW

**Comment by karol-kokoszka** [comment]
image

**Review by Michal-Leszczynski — APPROVED** [review]
Looks good!
Pleas create a follow-up PRs to merge those changes to `branch-3.2` and `branch-3.3`.

**Comment by karol-kokoszka** [comment]
Let's leave for the next release.

**Comment by karol-kokoszka** [comment]
It was deprecated way more before 3.2. 
On the other hand.... it doesn't require to do the release, it's just a change in the documentation.
OK, I can update it to 3.2 as well.

**Pull request merged**
