### PR TITLE
Add worker pool to repair

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
This is the first step in implementing #3611, as changing the approach to repair parallelism (while still integrating it with `sctool repair control`) requires freely control the size of the worker pool, which was lacking in the current implementation.

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka  could you take a look at that?

**Review by karol-kokoszka — APPROVED** [review]
:+1: Please trigger dtests and SCT before merging.

**Comment by Michal-Leszczynski** [comment]
SCT test [passed](https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/centos-sanity-test/1052/).

**Comment by Michal-Leszczynski** [comment]
All SM Dtests are currently failing because of not related [issue](https://github.com/scylladb/scylla-dtest/issues/3729).

**Comment by Michal-Leszczynski** [comment]
Passed [dtests](https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/manager-dtest/1359/).

**Pull request merged**
