### PR TITLE
Update dockerfile with missing packages

### PR DESCRIPTION
**Pull request by yaronkaikov**
Also unifing dockerfile package location so we can run docker build
command from dist folder

### CODE REVIEW

**Comment by mmatczuk** [comment]
Dockers are being built just fine with gorelaser.

**Comment by mmatczuk** [comment]
`bash-completion` is a recommended package for client maybe install with recommended.

**Comment by yaronkaikov** [comment]
we don't use golreaser for 2.5, only from 2.6

**Comment by yaronkaikov** [comment]
> `bash-completion` is a recommended package for client maybe install with recommended.

How do i add it?

**Comment by mmatczuk** [comment]
https://askubuntu.com/questions/117635/how-to-install-suggested-packages-in-apt-get

**Comment by yaronkaikov** [comment]
> https://askubuntu.com/questions/117635/how-to-install-suggested-packages-in-apt-get

@mmatczuk looks like it's not recommended but it's a dependency 
```
dpkg: dependency problems prevent configuration of scylla-manager-client:
 scylla-manager-client depends on bash-completion; however:
  Package bash-completion is not installed.
```

**Comment by mmatczuk** [comment]
The better.

**Comment by mmatczuk** [comment]
Actually I want to get rid of this dependency. In master we now support bash zsh and fish. We can add the dependency as you described.

**Comment by mmatczuk** [comment]
Why the PR is to 2.5 @yaronkaikov ?

**Comment by yaronkaikov** [comment]
> Why the PR is to 2.5 @yaronkaikov ?

I faced this when releasing 2.5. I need first to run `make release/deb` and after that to build docker images using the dockerfile. 
In master, i just use the goreleaser. Should i do it in master anyway?

**Comment by yaronkaikov** [comment]
@mmatczuk Fixed, now it's based on `master` , we should backport this to `2.5` in case we plan for more releases

**Pull request merged**
