### PR TITLE
fix(restore): post-restore repair to use max intensity and parallel

### LINKED ISSUE #3542: Run post-restore repair with max intensity
I think that SM should run post-restore repair with max intensity.
There are two reasons for that:
- restore procedure is usually the only thing putting pressure on the cluster
- recent changes to repair (SM 3.2) made it run slower (although with greater stability)

Right now SM runs the repair task with default intensity (1) and this change should speed-up the process.

### LINKED ISSUE #3823: Default parallelism and intensity for the repair after restore to MAX
This is the ghost issue, the real one is here https://github.com/scylladb/scylla-enterprise/issues/4118#issuecomment-2070890386

### PR DESCRIPTION
**Pull request by karol-kokoszka**
Fixes #3823 
Fixes #3542 

---

Please make sure that:
- Code is split to commits that address a single change
- Commit messages are informative
- Commit titles have module prefix
- Commit titles have issue nr. suffix

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
The reason for repair test failure: #3834.

**Comment by Michal-Leszczynski** [comment]
I'm fine with this change and I actually created identical PR in the past that was rejected because this [comment](https://github.com/scylladb/scylla-manager/pull/3541#issuecomment-1698659134). Did we validate that `sctool repair control` works on restore repair as intended? Or maybe this change should be introduced only alongside #3666?

**Comment by karol-kokoszka** [comment]
Right, would be good to have the `repair control` available for this post-restore.
Let's discuss on grooming.

**Comment by karol-kokoszka** [comment]
@Michal-Leszczynski did you have a chance to check if repair control works when the post-restore repair is on-going ?

**Pull request merged**
