### PR TITLE
Improve restore schema topology requirement

### LINKED ISSUE #3782: Imporve restore schema topology requirement
The problem description and suggested fix can be found here: https://github.com/scylladb/scylla-enterprise/issues/4072#issuecomment-2028570805.

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
Fixes #3782

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
@tzach @karol-kokoszka @annastuchlik This PR clarifies restore destination cluster topology requirements for both restoring schema and user data. Don't mind the test failures as they are already fixed on master and aren't related to this PR.

**Comment by Michal-Leszczynski** [comment]
Ping @tzach @karol-kokoszka @annastuchlik

**Review by karol-kokoszka — APPROVED** [review]
:+1:

**Comment by Michal-Leszczynski** [comment]
@annastuchlik I removed notes as requested. Can you take a look?

**Pull request merged**
