### PR TITLE
chore(deps): bumps project dependencies

### PR DESCRIPTION
**Pull request by charconstpointer**
closes https://github.com/scylladb/scylla-manager/issues/3416

This PR updates deps for scylla-manager 

And to address [this](https://github.com/scylladb/scylla-manager/issues/3416#issuecomment-1586944303) comment, we cannot do this since `scylladb/gocql` go.mod file declares its import path as `github.com/gocql/gocql` hence the need to replace it

### CODE REVIEW

**Review by karol-kokoszka — APPROVED** [review]
:+1:

**Comment by mykaul** [comment]
I still see:
```
github.com/gocql/gocql => github.com/scylladb/gocql v1.5.1-0.20210906110332-fb22d64efc33
```

so I don't think we've solved the issue I reported - can you please double check?

**Comment by karol-kokoszka** [comment]
@mykaul we cannot solve it in scylla-manager repository.
We have to use 
```
github.com/gocql/gocql => github.com/scylladb/gocql v1.5.1-0.20210906110332-fb22d64efc33
```
, because our shard-aware gocql driver still defines itself as `github.com/gocql/gocql`
see https://github.com/scylladb/gocql/blob/d522c40b18cf392be0795095cafb48e6236c0dc4/go.mod#L1

**Comment by mykaul** [comment]
> we can still bump the version, I'm working on it, I overlooked it initially

NOT for 3.1.1 please!

**Comment by karol-kokoszka** [comment]
3.1.1 is a different branch https://github.com/scylladb/scylla-manager/tree/branch-3.1
Whenever we patch-release or release minor, major version it's up to us to cherry-pick needed commits from master.

**Comment by mykaul** [comment]
> 3.1.1 is a different branch https://github.com/scylladb/scylla-manager/tree/branch-3.1 Whenever we patch-release or release minor, major version it's up to us to cherry-pick needed commits from master.

Of course-  I'm just making sure we don't plan on cherry-picking this to a release I want to see out today.

**Pull request merged**
