### PR TITLE
Don't rely SM side calculated replication strategy when filtering backup tables

### LINKED ISSUE #3989: Backup task scheduling regression in 3.3.1: `create backup target: create units: no keyspace matched criteria`
There seems to be a regression in backup task scheduling in 3.3.1 release, as updating the ScyllaDB Manager and ScyllaDB Manager Agent versions to 3.3.1 in Scylla Operator's test suite breaks all the backup-related tests.

Here's an example run: https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel/1825980285708144641#1:test-build-log.txt%3A1617

ScyllaCluster status snippet:
```
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: basic-tpz79
  namespace: e2e-test-scyllacluster-m4t6m-0-kf9mw
spec:
  agentRepository: docker.io/scylladb/scylla-manager-agent
  agentVersion: 3.3.1@sha256:beb544f6049cbae71a672cd6135ec9338ed2dd4deb8db3d205b093355d42bda5
  backups:
  - location:
    - gcs:so-c42d9a33-dc98-45d3-bc1b-37134152b877
    name: backup
    numRetries: 3
    retention: 2
  datacenter:
    name: us-east-1
    racks:
      members: 1
      name: us-east-1a
status:
  backups:
  - error: 'Post "http://scylla-manager/api/v1/cluster/3ea765e4-4788-4801-94d1-fd40d4cac18e/tasks":
      context deadline exceeded (Client.Timeout exceeded while awaiting headers)'
    name: backup
  managerId: 3ea765e4-4788-4801-94d1-fd40d4cac18e
```
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel/1825980285708144641/artifacts/e2e/namespaces/e2e-test-scyllacluster-m4t6m-0-kf9mw/scyllaclusters.scylla.scylladb.com/basic-tpz79.yaml

ScyllaDB Manager logs snippet:
```
2024-08-20T19:59:11.459897955Z {"L":"INFO","T":"2024-08-20T19:59:11.459Z","N":"backup","M":"Generating backup target","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.630306392Z {"L":"INFO","T":"2024-08-20T19:59:11.464Z","N":"cluster.client","M":"Checking hosts connectivity","hosts":["10.45.225.58"],"_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.630324562Z {"L":"INFO","T":"2024-08-20T19:59:11.465Z","N":"cluster.client","M":"Host check OK","host":"10.45.225.58","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.630331402Z {"L":"INFO","T":"2024-08-20T19:59:11.465Z","N":"cluster.client","M":"Done checking hosts connectivity","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.630337342Z {"L":"INFO","T":"2024-08-20T19:59:11.465Z","N":"backup","M":"Checking accessibility of remote locations","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.920333411Z {"L":"INFO","T":"2024-08-20T19:59:11.920Z","N":"backup","M":"Location check OK","host":"10.45.225.58","location":"gcs:so-c42d9a33-dc98-45d3-bc1b-37134152b877","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.920349561Z {"L":"INFO","T":"2024-08-20T19:59:11.920Z","N":"backup","M":"Done checking accessibility of remote locations","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.920354171Z {"L":"INFO","T":"2024-08-20T19:59:11.920Z","N":"cluster","M":"Get session","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.920367211Z {"L":"INFO","T":"2024-08-20T19:59:11.920Z","N":"cluster","M":"Creating new Scylla HTTP client","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.925837290Z {"L":"INFO","T":"2024-08-20T19:59:11.925Z","N":"cluster.client","M":"Measuring datacenter latencies","dcs":["us-east-1"],"_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
2024-08-20T19:59:11.980139476Z {"L":"INFO","T":"2024-08-20T19:59:11.979Z","N":"http","M":"POST /api/v1/cluster/3ea765e4-4788-4801-94d1-fd40d4cac18e/tasks","from":"10.45.225.33:38892","status":500,"bytes":128,"duration":"525ms","error":"create backup target: create units: no keyspace matched criteria","_trace_id":"wqeZFFkzTmqHNU6hqI2AlA"}
...
2024-08-20T19:59:15.882660502Z {"L":"INFO","T":"2024-08-20T19:59:15.873Z","N":"backup","M":"Generating backup target","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:15.882664932Z {"L":"INFO","T":"2024-08-20T19:59:15.880Z","N":"cluster.client","M":"Checking hosts connectivity","hosts":["10.45.225.58"],"_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:15.882669242Z {"L":"INFO","T":"2024-08-20T19:59:15.881Z","N":"cluster.client","M":"Host check OK","host":"10.45.225.58","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:15.882673012Z {"L":"INFO","T":"2024-08-20T19:59:15.881Z","N":"cluster.client","M":"Done checking hosts connectivity","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:15.882676452Z {"L":"INFO","T":"2024-08-20T19:59:15.881Z","N":"backup","M":"Checking accessibility of remote locations","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.429315241Z {"L":"INFO","T":"2024-08-20T19:59:16.429Z","N":"backup","M":"Location check OK","host":"10.45.225.58","location":"gcs:so-c42d9a33-dc98-45d3-bc1b-37134152b877","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.429429231Z {"L":"INFO","T":"2024-08-20T19:59:16.429Z","N":"backup","M":"Done checking accessibility of remote locations","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.429547601Z {"L":"INFO","T":"2024-08-20T19:59:16.429Z","N":"cluster","M":"Get session","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.429642821Z {"L":"INFO","T":"2024-08-20T19:59:16.429Z","N":"cluster","M":"Creating new Scylla HTTP client","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.435372620Z {"L":"INFO","T":"2024-08-20T19:59:16.435Z","N":"cluster.client","M":"Measuring datacenter latencies","dcs":["us-east-1"],"_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
2024-08-20T19:59:16.481457357Z {"L":"INFO","T":"2024-08-20T19:59:16.481Z","N":"http","M":"POST /api/v1/cluster/3ea765e4-4788-4801-94d1-fd40d4cac18e/tasks","from":"10.45.225.33:51368","status":500,"bytes":128,"duration":"609ms","error":"create backup target: create units: no keyspace matched criteria","_trace_id":"f1Dx9UHcRqC-Kmuj2bIvZw"}
...
2024-08-20T19:59:18.534436572Z {"L":"INFO","T":"2024-08-20T19:59:18.234Z","N":"backup","M":"Generating backup target","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.534442732Z {"L":"INFO","T":"2024-08-20T19:59:18.249Z","N":"cluster.client","M":"Checking hosts connectivity","hosts":["10.45.225.58"],"_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.534460302Z {"L":"INFO","T":"2024-08-20T19:59:18.251Z","N":"cluster.client","M":"Host check OK","host":"10.45.225.58","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.534466422Z {"L":"INFO","T":"2024-08-20T19:59:18.252Z","N":"cluster.client","M":"Done checking hosts connectivity","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.534471892Z {"L":"INFO","T":"2024-08-20T19:59:18.252Z","N":"backup","M":"Checking accessibility of remote locations","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.872944186Z {"L":"INFO","T":"2024-08-20T19:59:18.872Z","N":"backup","M":"Location check OK","host":"10.45.225.58","location":"gcs:so-c42d9a33-dc98-45d3-bc1b-37134152b877","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.872964146Z {"L":"INFO","T":"2024-08-20T19:59:18.872Z","N":"backup","M":"Done checking accessibility of remote locations","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.872971497Z {"L":"INFO","T":"2024-08-20T19:59:18.872Z","N":"cluster","M":"Get session","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.872977317Z {"L":"INFO","T":"2024-08-20T19:59:18.872Z","N":"cluster","M":"Creating new Scylla HTTP client","cluster_id":"3ea765e4-4788-4801-94d1-fd40d4cac18e","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.902458954Z {"L":"INFO","T":"2024-08-20T19:59:18.894Z","N":"cluster.client","M":"Measuring datacenter latencies","dcs":["us-east-1"],"_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
2024-08-20T19:59:18.953326000Z {"L":"INFO","T":"2024-08-20T19:59:18.953Z","N":"http","M":"POST /api/v1/cluster/3ea765e4-4788-4801-94d1-fd40d4cac18e/tasks","from":"10.45.225.33:51380","status":500,"bytes":128,"duration":"723ms","error":"create backup target: create units: no keyspace matched criteria","_trace_id":"hitHSwy9RtmbM7TtbqPcNw"}
```
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel/1825980285708144641/artifacts/must-gather/0/namespaces/scylla-manager/pods/scylla-manager-79cf8b8677-hq7gk/scylla-manager.current

ScyllaDB Manager Agent logs: https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel/1825980285708144641/artifacts/e2e/namespaces/e2e-test-scyllacluster-m4t6m-0-kf9mw/pods/basic-tpz79-us-east-1-us-east-1a-0/scylla-manager-agent.current

All artifacts: https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2089/pull-scylla-operator-master-e2e-gke-parallel/1825980285708144641/artifacts/

All of our tests seem to be failing with **create backup target: create units: no keyspace matched criteria** error, which wasn't the case with earlier releases. 

ScyllaDB Manager version: 3.3.1
ScyllaDB version: tested OS 6.0.1, 6.1.0 and Enterprise 2024.1.5, 2024.1.7
ScyllaDB Manager client version: tested 3.2.8 and 3.3.1

Xref: https://github.com/scylladb/scylla-operator/pull/2089#issuecomment-2301558640

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
This PR adds a way to filter keyspaces by:
- all keyspaces
- user keyspaces
- non local keyspaces

And uses it in backup table filtering in order to fix #3989.

Fixes #3989

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka This PR is ready for review!

**Comment by karol-kokoszka** [comment]
> In terms of validating this PR against operator tests, it can be done when the jenkins build job is fixed.

Yes, let's wait with merge until it's possible to validate the solution.

**Comment by Michal-Leszczynski** [comment]
TMP PR running Operator CI: https://github.com/scylladb/scylla-operator/pull/2104.

**Comment by Michal-Leszczynski** [comment]
Failure comes from known flake: https://github.com/scylladb/scylla-manager/issues/3961.

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka operator CI passed, can we merge?

**Review by karol-kokoszka — APPROVED** [review]

**Comment by karol-kokoszka** [comment]
> @karol-kokoszka operator CI passed, can we merge?

sure, go on

**Pull request merged**
