### PR TITLE
doc: remove the retention-days option from 3.0

### PR DESCRIPTION
**Pull request by annastuchlik**
Fixes https://github.com/scylladb/scylladb/issues/13617
The option is only introduced in version 3.1 and should be removed from the docs for version 3.0.

### CODE REVIEW

**Comment by karol-kokoszka** [comment]
@annastuchlik `retention-days` is available in `sctool_backup_update.yaml` as well.
Please remove it from here too and I'll merge it to branch-3.0

**Comment by annastuchlik** [comment]
@karol-kokoszka I've removed it from sctool_backup.yaml. 
The content from that file is included in the docs - when you update a description in sctool_backup.yaml, it's also updated in the docs.

**Comment by karol-kokoszka** [comment]
@annastuchlik What I'm trying to say is that `retention-days` option is available in `backup update` command as well. And it has to be removed from there too.
I can do it by myself. Np.

**Comment by karol-kokoszka** [comment]
@annastuchlik 
OK, I cannot do it by myself, because you proposed PR from your fork.
Please update `sctool_backup_update.yaml` file as well then.

**Comment by annastuchlik** [comment]
@karol-kokoszka Please update the files according to the practices in this repo (not using a fork). 
I'm closing this PR as not sufficient.

**Pull request closed without merging**
