### PR TITLE
backup: merge backup/paths to backupspec/paths

### PR DESCRIPTION
**Pull request by karol-kokoszka**
Merges backup/paths.go with backup/backupspec/paths that are serving the same purpose

---

"Only the Best is Good Enough." - LEGO company motto

Please make sure that:
- Code is split to commits that address a single change
- Commit messages are informative
- Commit titles have module prefix
- Commit titles have issue nr. suffix

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
Why have you merged commit which failed Integration Tests because the code didn't compile?!?

**Comment by karol-kokoszka** [comment]
Wanted to have it faster on master...
I had to do the follow up anyway.

**Comment by Michal-Leszczynski** [comment]
That's ok, but let's try to wait for the checks to end before merging future PRs

**Comment by karol-kokoszka** [comment]
sure, don't worry, no one should use the latest master
stable/released scylla-manager packages is something what customer should use

**Pull request merged**
