### PR TITLE
update master version to 3.1-dev

### PR DESCRIPTION
**Pull request by Annamikhlin**
update master dev version number from 3.0-dev to 3.1-dev

closes: https://github.com/scylladb/scylla-pkg/issues/3209

### CODE REVIEW

**Review by yaronkaikov — APPROVED** [review]
LGTM

**Review by karol-kokoszka — APPROVED** [review]
:+1:

**Comment by benipeled** [comment]
@Annamikhlin isn't this update should be done automatically as part of the release? are we missed/missing something in the manager-release pipeline?

**Comment by Annamikhlin** [comment]
> @Annamikhlin isn't this update should be done automatically as part of the release? are we missed/missing something in the manager-release pipeline?

We are updaing the file part of the manager-release in specific branch and it works correctly. 
The same file in master should be also updated part of new branch creation. 

@karol-kokoszka - is it part of your procedure to update the version in master during new branch creation?

**Pull request merged**
