### PR TITLE
Tablet repair

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
WIP - have yet to test it against Scylla with tablets enabled.

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
I encountered:
```
agent [HTTP 500] std::runtime_error (The ranges option is not supported for tablet repair)"
```
when running repair against `scylla-nightly:latest`.

**Comment by asias** [comment]
> I encountered:
> 
> ```
> agent [HTTP 500] std::runtime_error (The ranges option is not supported for tablet repair)"
> ```
> 
> when running repair against `scylla-nightly:latest`.

https://github.com/scylladb/scylladb/pull/17436
https://github.com/scylladb/scylladb/pull/17571

**Comment by asias** [comment]
@Michal-Leszczynski I saw you closed the PR. Are the relevant patches merged already? Btw, you can start to test SM with the latest branch https://github.com/scylladb/scylladb/pull/17767. It contains all the necessary options support for SM.

**Comment by Michal-Leszczynski** [comment]
This PR was closed because it was rebased on other repair related PR that was laying ground work for tablet repair and it got heavily refactored. I will get what's useful from this PR and test SM repair on tablets table today.

**Comment by Michal-Leszczynski** [comment]
@asias I see that the host param is not suported. SM repair uses the host param in order to filter dcs and down nodes. It can be changed to use the dc param for dc filtering, but what about filtering out down nodes?

**Pull request closed without merging**
