### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by GavinJE**
Line 34. "Link is being repaired, please be patient" added.

---

"Only the Best is Good Enough." - LEGO company motto

Please make sure that:
- Code is split to commits that address a single change
- Commit messages are informative
- Commit titles have module prefix
- Commit titles have issue nr. suffix

### CODE REVIEW

**Comment by GavinJE** [comment]
The link in line 34 does not work due to a bug in the code. The code needs to be changed because the http command is not active.

**Comment by mmatczuk** [comment]
What http command do you mean?

**Comment by GavinJE** [comment]
Hi Michal.

When you hover over the link, no http precursor is seen and the link when
clicked does not function.

**Comment by mmatczuk** [comment]
It does work when the ssh tunnel is in place, doesn't it?

**Comment by GavinJE** [comment]
Not sure about that. Sorry.

**Comment by guy9** [comment]
Thanks @GavinJE , @mmatczuk , this is a false positive and can be closed.

**Comment by GavinJE** [comment]
@guy9 maintains this link only works locally and therefore is not an error. Pull request therefore closed.

**Pull request closed without merging**
