### PR TITLE
docs: update theme 1.3

### PR DESCRIPTION
**Pull request by dgarcia360**
Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/548

ScyllaDB Sphinx Theme 1.3 is now released 🥳 

We’ve added better redirects support and introduced numerous UI updates.

You can read more about all notable changes [here](https://sphinx-theme.scylladb.com/stable/upgrade/CHANGELOG.html#aug-2022).

## How to test this PR

1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).

2. Enter the docs folder, and run:

```
make preview
````

4. Open  http://localhost:5500 with your favorite browser. The doc should render without errors, and the version should be Sphinx Theme version (see the footer) must be ``1.3.x``:

image

### CODE REVIEW

**Comment by dgarcia360** [comment]
@annastuchlik @tzach please review

**Comment by karol-kokoszka** [comment]
@annastuchlik @tzach Can you review ? Is this PR still valid ? Do you want me to merge it ?

**Comment by annastuchlik** [comment]
@karol-kokoszka Thanks for bringing this up. This PR is definitely valid as it updates the Sphinx theme. I've just reviewed it, and it looks great. 
It's ready to be merged.

**Review by annastuchlik — APPROVED** [review]
LGTM

**Review by karol-kokoszka — APPROVED** [review]

**Pull request merged**
