### PR TITLE
Metrics: scheduler, introduced 'scylla_manager_scheduler_last_duration'

### LINKED ISSUE #3587: Add metric for last run druation
As described in this [comment](https://github.com/scylladb/scylla-monitoring/issues/2043#issuecomment-1735262713), it would be useful to have a metric like `scylla_manager_scheduler_last_duration` (similar to already existing `scylla_manager_scheduler_last_success`).

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
Fixes #3587

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
First repair run:
```
# HELP scylla_manager_scheduler_last_duration Duration of the last successful run in nanoseconds. This is a simple difference between end and start time (e.g. the time when the task was paused is also included).
# TYPE scylla_manager_scheduler_last_duration gauge
scylla_manager_scheduler_last_duration{cluster="d46c2d7c-8224-4a01-a8f3-6e241b83a819",task="16194a77-d082-4952-8eba-de00b6b45715",type="repair"} 3.5618654887e+10
scylla_manager_scheduler_last_duration{cluster="d46c2d7c-8224-4a01-a8f3-6e241b83a819",task="1f4f60b1-8865-4179-95c8-bf2a75bd3d32",type="healthcheck"} 5.693941e+06
scylla_manager_scheduler_last_duration{cluster="d46c2d7c-8224-4a01-a8f3-6e241b83a819",task="3e479370-85a7-4582-bf92-191dc23bb90e",type="healthcheck"} 8.732537e+06
scylla_manager_scheduler_last_duration{cluster="d46c2d7c-8224-4a01-a8f3-6e241b83a819",task="568c3931-e752-4865-b334-9602c7d58c8f",type="healthcheck"} 1.1454387e+07
```
Second repair run:
```
# HELP scylla_manager_scheduler_last_duration Duration of the last successful run in nanoseconds. This is a simple difference between end and start time (e.g. the time when the task was paused is also included).
# TYPE scylla_manager_scheduler_last_duration gauge
scylla_manager_scheduler_last_duration{cluster="d46c2d7c-8224-4a01-a8f3-6e241b83a819",task="16194a77-d082-4952-8eba-de00b6b45715",type="repair"} 3.5298179922e+10
scylla_manager_scheduler_last_duration{cluster="d46c2d7c-8224-4a01-a8f3-6e241b83a819",task="1f4f60b1-8865-4179-95c8-bf2a75bd3d32",type="healthcheck"} 4.533699e+06
scylla_manager_scheduler_last_duration{cluster="d46c2d7c-8224-4a01-a8f3-6e241b83a819",task="3e479370-85a7-4582-bf92-191dc23bb90e",type="healthcheck"} 6.198252e+06
scylla_manager_scheduler_last_duration{cluster="d46c2d7c-8224-4a01-a8f3-6e241b83a819",task="568c3931-e752-4865-b334-9602c7d58c8f",type="healthcheck"} 1.0800014e+07
```

**Comment by Michal-Leszczynski** [comment]
There is a bigger problem with interpreting scheduler metrics.
For example, `scylla_manager_scheduler_last_success` shows timestamp of the last successful *run*.
So if we start a 1h backup at 10:00, pause it at 10:55, and then instantly resume it, we would get `scylla_manager_scheduler_last_success` with 10:55 timestamp (not the 10:00 when the task was originally started). The same goes for retries.

This also means that proposed approach would report `scylla_manager_scheduler_last_duration` with 5min (not the more intuitive 1h).

This is correct in terms of how SM understands task *run*, but it seems like it's less useful for the user and monitoring (monitoring [requirements](https://github.com/scylladb/scylla-monitoring/issues/2043)).

This is also the case for displaying task duration in `sctool progress` (only the duration of the last run is displayed).

The question is, is this acceptable?
Is it ok in terms of mentioned monitoring requirements?

**Comment by Michal-Leszczynski** [comment]
Start and stop repair task:
```
Run:            69cd91b1-5deb-11ee-9d8f-0892040e83bb
Status:         STOPPED
Start time:     28 Sep 23 12:40:16 CEST
End time:       28 Sep 23 12:40:39 CEST
Duration:       22s
Progress:       7%
```
Resume repair task:
```
Run:            87a22c01-5deb-11ee-9d90-0892040e83bb
Status:         DONE
Start time:     28 Sep 23 12:41:06 CEST
End time:       28 Sep 23 12:41:19 CEST
Duration:       12s
Progress:       100%
```

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka what are your thoughts about that?

**Comment by karol-kokoszka** [comment]
It should show the last success of the full task execution, not the task run.

**Comment by amnonh** [comment]
How would we use those metrics?
If we are reporting multiple tasks at the same time (see the example with multiple healthcheck)
At least for centralized/datadog integration we would like to collect one metric per type, the task id is good for debuging but in this case, it's not clear how to aggregate the values to get the last one

**Comment by Michal-Leszczynski** [comment]
> How would we use those metrics?
If we are reporting multiple tasks at the same time (see the example with multiple healthcheck)
At least for centralized/datadog integration we would like to collect one metric per type, the task id is good for debuging but in this case, it's not clear how to aggregate the values to get the last one

But isn't `taskID` also important for monitoring? E.g. creating an alert for a long running repair/backup.
In this case we would like to compare currently running repair task only with it's previous run duration, but not with any repair duration. This could create problem if there are 2 repairs scheduled, but one of them targets only some small system tables (so it will be short), and another targets huge user tables (so it will be long).

**Comment by amnonh** [comment]
@Michal-Leszczynski from the centralized monitoring perspective, I don't see how to use it

**Comment by Michal-Leszczynski** [comment]
> @Michal-Leszczynski from the centralized monitoring perspective, I don't see how to use it

I'm not sure how alert rules are written, but would it be possible to do something like:
```
tasks = full labels ("cluster", "type", "task") of 'scylla_manager_scheduler_run_indicator' metric.
for t in tasks:
  if current_duration(t) > scylla_manager_scheduler_last_duration(t):
    alert()
```
where `current_duration(t)` could be calculated based on the time since `scylla_manager_scheduler_run_indicator(t) == 1`.

Is this something that can be done on the monitoring side (assuming that SM provides correct `scylla_manager_scheduler_last_duration` metric)? As I said before, we can't really ignore task IDs here as it could lead to false alerts.

**Comment by Michal-Leszczynski** [comment]
Example with two repairs (interrupted a 2 times `eeb69ae2-65dc-11ee-a4dd-0892040e83bb`, uninterrupted `61c4bb85-65dc-11ee-a4da-0892040e83bb`).

Metrics:
```
scylla_manager_scheduler_last_duration{cluster="e7f28cec-9b24-4a7c-8d18-fbdc1a14f316",task="0d31345d-07ce-4226-a427-09945d84f129",type="repair"} 3.592261957e+10
scylla_manager_scheduler_last_duration{cluster="e7f28cec-9b24-4a7c-8d18-fbdc1a14f316",task="e3a1df0f-09ba-4217-8969-5cae0bbc2026",type="repair"} 3.4555992885e+10
```
where `sctool progress` output looks like (it still prints only last run duration):
```
[miles@fedora scylla-manager]$ ./sctool progress -c myc repair/0d31345d-07ce-4226-a427-09945d84f129
Run:            eeb69ae2-65dc-11ee-a4dd-0892040e83bb
Status:         DONE
Start time:     08 Oct 23 15:16:46 CEST
End time:       08 Oct 23 15:16:56 CEST
Duration:       10s
Progress:       100%
```
```
[miles@fedora scylla-manager]$ ./sctool progress -c myc repair/e3a1df0f-09ba-4217-8969-5cae0bbc2026
Run:            61c4bb85-65dc-11ee-a4da-0892040e83bb
Status:         DONE
Start time:     08 Oct 23 15:12:50 CEST
End time:       08 Oct 23 15:13:24 CEST
Duration:       34s
Progress:       100%
```

**Comment by amnonh** [comment]
@Michal-Leszczynski for alerts, maybe we can use some hard coded values, or compare a value with a previous, not sure.
My problem is with collecting the value to a centralized location, which is part of the motiviation for the issue.

From a centalized location metrics perspective, we are looking for a graph that shows repair duration. What is the typical number of tasks a cluster have?

**Comment by Michal-Leszczynski** [comment]
> From a centalized location metrics perspective, we are looking for a graph that shows repair duration. What is the typical number of tasks a cluster have?

I don't have any customer data to answer that, but I would expect that most clusters have 1 repair task, but it's not uncommon to have 2 or 3 of them.
@karol-kokoszka  @tzach do you know the answer to this question?

**Comment by karol-kokoszka** [comment]
> From a centalized location metrics perspective, we are looking for a graph that shows repair duration. What is the typical number of tasks a cluster have?

Usually it's just a single repair task per cluster.
But there is no limitation in scylla-manager regarding number of repair tasks defined. There may be more than 1.

**Comment by amnonh** [comment]
@karol-kokoszka  ok, so in the context of the cloud, what is the typicall number of repair and backup tasks?

**Comment by karol-kokoszka** [comment]
@amnonh for cloud, it's usually 1 repair task scheduled to be triggered once a week. Plus one backup task scheduled to be triggered once a day.

But still, this is the default configuration which can be updated/changed by devops on customer request.

**Pull request closed without merging**
