### PR TITLE
manager-build: fix configuration to match new docker version

### PR DESCRIPTION
**Pull request by yaronkaikov**
Following the upgrade of all Jenkins nodes to Fedora40, a few configuration issues popped up

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
@yaronkaikov I see that a single [master build job](https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/manager-build/785/) was successful. Is there any way to reproduce this success?
The issue with SM builds prevents us from testing restore improvements.

I also tried to use the [3.3 build job](https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.3/job/manager-build/52/) with a separate branch rebased on branch-3.3, but it failed with merge conflicts. How is that possible?

**Comment by yaronkaikov** [comment]
> @yaronkaikov I see that a single [master build job](https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/manager-build/785/) was successful. Is there any way to reproduce this success? The issue with SM builds prevents us from testing restore improvements.
> 
> I also tried to use the [3.3 build job](https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.3/job/manager-build/52/) with a separate branch rebased on branch-3.3, but it failed with merge conflicts. How is that possible?

We will need to get this one in and backport to 3.3

**Comment by Michal-Leszczynski** [comment]
> We will need to get this one in and backport to 3.3

@yaronkaikov is this PR ready to be merged, or are you still working on it?

**Comment by yaronkaikov** [comment]
> > We will need to get this one in and backport to 3.3
> 
> @yaronkaikov is this PR ready to be merged, or are you still working on it?

from my POV it can be merged, I have verified with https://jenkins.scylladb.com/job/manager-master/job/build-debug/72/

**Review by Annamikhlin — APPROVED** [review]
LGTM

**Review by Michal-Leszczynski — APPROVED** [review]

**Review by karol-kokoszka — APPROVED** [review]

**Pull request merged**
