### PR TITLE
Clarify details about sctool stop --disable

### PR DESCRIPTION
**Pull request by GeoffMontee**
---

Please make sure that:
- Code is split to commits that address a single change
- Commit messages are informative
- Commit titles have module prefix
- Commit titles have issue nr. suffix

### CODE REVIEW

**Comment by Michal-Leszczynski** [comment]
Hi, thanks for the contribution!
We have a certain way of working with docs (the file you changed is autogenerated from other files), so I will change this PR (or reopen another one), so that this change is included properly into our codebase.

**Comment by GeoffMontee** [comment]
Hi @Michal-Leszczynski ,

Thanks! I will try to watch for your changes, so I will know how to properly contribute to the docs next time.

**Comment by GeoffMontee** [comment]
Hi @Michal-Leszczynski,

I used `grep` to find the other instance of the usage text, and I updated that text and amended the commit. Does this look right now?

**Comment by Michal-Leszczynski** [comment]
Hi @GeoffMontee, sorry for not responding for a long time.
I pushed small changes to your branch.

The general workflow for editing SM docs looks like that:

1. If the change is about [CLI sctool section](https://manager.docs.scylladb.com/stable/sctool/index.html#), you need to find corresponding command docs under `/pkg/command/<command_name>/res.yaml`, edit it, and run `make docs` from repo root dir. This will re-generate all doc related files that are influenced by your change.
2. If the change is about something else, you need to find corresponding doc file under `/docs/source/<path_to_changed_docs>`. This does not require any additional steps.

Anyway, thanks for the contribution and sorry again for leaving it for so long!

**Comment by GeoffMontee** [comment]
Awesome, thank you for the information!

**Review by karol-kokoszka — APPROVED** [review]

**Pull request merged**
