### PR TITLE
refactor(swagger): drop unused API

### PR DESCRIPTION
**Pull request by tchaikov**
"/storage_service/describe_ring/" returns the token range of a random keyspace. this API is never used in production. what is used is is cousin which accepts a mandatory keyspace path parameter, like "/storage_service/describe_ring/{keyspace}", so let's drop it in scylla-manager, we will drop this API in scylla as well.

---

Please make sure that:
- Code is split to commits that address a single change
- Commit messages are informative
- Commit titles have module prefix
- Commit titles have issue nr. suffix

### CODE REVIEW

**Comment by tchaikov** [comment]
```
 --- Then: Scylla is restarted on host: 2001:0db9:0200:0000:0000:0000:0000:0013
--- Then: cluster is restarted
--- And: validate that restore preserves tombstone_gc mode
--- When: query contents of restored table
    service_restore_integration_test.go:1436: {alternator_Tab_le-With1.da_sh2-aNd.d33ot.- Tab_le-With1.da_sh2-aNd.d33ot.- key}, srcCount = 0, dstCount = 0
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::23:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::21:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::22:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::13:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::11:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::12:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to connect to any ring node: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: control falling back to initial contact points.
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::11:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::12:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::13:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::21:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::22:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to dial control conn 2001:db9:100::23:9042: Username and/or password are incorrect
2024/02/07 06:44:02 gocql: unable to reconnect control connection: Username and/or password are incorrect
    service_restore_integration_test.go:1443: grant alter permission: <table alternator_Tab_le-With1.da_sh2-aNd.d33ot.-.Tab_le-With1.da_sh2-aNd.d33ot.-> doesn't exist.
--- FAIL: TestRestoreFullAlternatorIntegration (1087.19s)
FAIL
make: *** [Makefile:140: pkg-integration-test] Error 1
```

i don't think the failure is relevant.

**Comment by karol-kokoszka** [comment]
Hey @tchaikov . Broken integration tests are not related to this PR. It's a known issue of restoring schema with Scylla 5.4.

**Review by karol-kokoszka — CHANGES_REQUESTED** [review]
Changes you want to introduce with this PR are made on auto-generated code only.
You need to do it different way.
Please remove the endpoint from https://github.com/scylladb/scylla-manager/blob/master/swagger/scylla_v1.json and then just
```
cd swagger
make gen/scylla/v1
```

Otherwise, your fix will be overwritten by the consecutive `make generate` call.

**Review by karol-kokoszka — APPROVED** [review]
:+1:

**Pull request merged**
